### ISSUE TITLE
Fullchain Cert Generation, relative path assumption

### ISSUE THREAD

**Issue by FuzzySecurity** [outflanknl/RedELK#181]
This line in the install script assumes a relative path for `config.cnf`

https://github.com/outflanknl/RedELK/blob/master/elkserver/install-elkserver.sh#L437

In my case that was not correct, during deployment I use Ansible regex replace to put in the correct full path.

```yml
  - name: Fix beta v4 deployment path bug
    replace:
      path: /opt/RedELK-Install/install-elkserver.sh
      regexp: '\.\.\/certs\/config\.cnf'
      replace: '/opt/RedELK/build/RedELK-2.0.0-beta.4/certs/config.cnf'
```
